import { describe, expect, test } from 'vitest'

import {
  type Direction,
  type Position,
  type Vec,
  walk,
} from '@/index'

describe('walk', () => {
  const tests: {
    from: Position,
    direction: Direction,
    expected: Position[],
  }[] = [
    { from: 'a1', direction: 0, expected: ['a2', 'a3', 'a4', 'a5', 'a6'] },
    { from: 'a1', direction: 1, expected: ['b3', 'c5', 'd7', 'e9', 'f11'] },
    { from: 'a1', direction: 2, expected: ['b2', 'c3', 'd4', 'e5', 'f6', 'g6', 'h6', 'i6', 'k6', 'l6'] },
    { from: 'a1', direction: 3, expected: ['c2', 'e3', 'g3', 'i2', 'l1'] },
    { from: 'a1', direction: 4, expected: ['b1', 'c1', 'd1', 'e1', 'f1'] },
    { from: 'a1', direction: 5, expected: [] },
    { from: 'a1', direction: 6, expected: [] },
    { from: 'a1', direction: 7, expected: [] },
    { from: 'a1', direction: 8, expected: [] },
    { from: 'a1', direction: 9, expected: [] },
    { from: 'a1', direction: 10, expected: [] },
    { from: 'a1', direction: 11, expected: [] },

    { from: 'a2', direction: 0, expected: ['a3', 'a4', 'a5', 'a6'] },
    { from: 'a2', direction: 1, expected: ['b4', 'c6', 'd8', 'e10'] },
    { from: 'a2', direction: 2, expected: ['b3', 'c4', 'd5', 'e6', 'f7', 'g7', 'h7', 'i7', 'k7'] },
    { from: 'a2', direction: 3, expected: ['c3', 'e4', 'g4', 'i3', 'l2'] },
    { from: 'a2', direction: 4, expected: ['b2', 'c2', 'd2', 'e2', 'f2', 'g1'] },
    { from: 'a2', direction: 5, expected: ['b1'] },
    { from: 'a2', direction: 6, expected: ['a1'] },
    { from: 'a2', direction: 7, expected: [] },
    { from: 'a2', direction: 8, expected: [] },
    { from: 'a2', direction: 9, expected: [] },
    { from: 'a2', direction: 10, expected: [] },
    { from: 'a2', direction: 11, expected: [] },

    { from: 'a3', direction: 0, expected: ['a4', 'a5', 'a6'] },
    { from: 'a3', direction: 1, expected: ['b5', 'c7', 'd9'] },
    { from: 'a3', direction: 2, expected: ['b4', 'c5', 'd6', 'e7', 'f8', 'g8', 'h8', 'i8'] },
    { from: 'a3', direction: 3, expected: ['c4', 'e5', 'g5', 'i4', 'l3'] },
    { from: 'a3', direction: 4, expected: ['b3', 'c3', 'd3', 'e3', 'f3', 'g2', 'h1'] },
    { from: 'a3', direction: 5, expected: ['b2', 'c1'] },
    { from: 'a3', direction: 6, expected: ['a2', 'a1'] },
    { from: 'a3', direction: 7, expected: [] },
    { from: 'a3', direction: 8, expected: [] },
    { from: 'a3', direction: 9, expected: [] },
    { from: 'a3', direction: 10, expected: [] },
    { from: 'a3', direction: 11, expected: [] },

    { from: 'a4', direction: 0, expected: ['a5', 'a6'] },
    { from: 'a4', direction: 1, expected: ['b6', 'c8'] },
    { from: 'a4', direction: 2, expected: ['b5', 'c6', 'd7', 'e8', 'f9', 'g9', 'h9'] },
    { from: 'a4', direction: 3, expected: ['c5', 'e6', 'g6', 'i5', 'l4'] },
    { from: 'a4', direction: 4, expected: ['b4', 'c4', 'd4', 'e4', 'f4', 'g3', 'h2', 'i1'] },
    { from: 'a4', direction: 5, expected: ['b3', 'c2', 'd1'] },
    { from: 'a4', direction: 6, expected: ['a3', 'a2', 'a1'] },
    { from: 'a4', direction: 7, expected: [] },
    { from: 'a4', direction: 8, expected: [] },
    { from: 'a4', direction: 9, expected: [] },
    { from: 'a4', direction: 10, expected: [] },
    { from: 'a4', direction: 11, expected: [] },

    { from: 'a5', direction: 0, expected: ['a6'] },
    { from: 'a5', direction: 1, expected: ['b7'] },
    { from: 'a5', direction: 2, expected: ['b6', 'c7', 'd8', 'e9', 'f10', 'g10'] },
    { from: 'a5', direction: 3, expected: ['c6', 'e7', 'g7', 'i6', 'l5'] },
    { from: 'a5', direction: 4, expected: ['b5', 'c5', 'd5', 'e5', 'f5', 'g4', 'h3', 'i2', 'k1'] },
    { from: 'a5', direction: 5, expected: ['b4', 'c3', 'd2', 'e1'] },
    { from: 'a5', direction: 6, expected: ['a4', 'a3', 'a2', 'a1'] },
    { from: 'a5', direction: 7, expected: [] },
    { from: 'a5', direction: 8, expected: [] },
    { from: 'a5', direction: 9, expected: [] },
    { from: 'a5', direction: 10, expected: [] },
    { from: 'a5', direction: 11, expected: [] },

    { from: 'a6', direction: 0, expected: [] },
    { from: 'a6', direction: 1, expected: [] },
    { from: 'a6', direction: 2, expected: ['b7', 'c8', 'd9', 'e10', 'f11'] },
    { from: 'a6', direction: 3, expected: ['c7', 'e8', 'g8', 'i7', 'l6'] },
    { from: 'a6', direction: 4, expected: ['b6', 'c6', 'd6', 'e6', 'f6', 'g5', 'h4', 'i3', 'k2', 'l1'] },
    { from: 'a6', direction: 5, expected: ['b5', 'c4', 'd3', 'e2', 'f1'] },
    { from: 'a6', direction: 6, expected: ['a5', 'a4', 'a3', 'a2', 'a1'] },
    { from: 'a6', direction: 7, expected: [] },
    { from: 'a6', direction: 8, expected: [] },
    { from: 'a6', direction: 9, expected: [] },
    { from: 'a6', direction: 10, expected: [] },
    { from: 'a6', direction: 11, expected: [] },

    { from: 'b7', direction: 0, expected: [] },
    { from: 'b7', direction: 1, expected: [] },
    { from: 'b7', direction: 2, expected: ['c8', 'd9', 'e10', 'f11'] },
    { from: 'b7', direction: 3, expected: ['d8', 'f9', 'h8', 'k7'] },
    { from: 'b7', direction: 4, expected: ['c7', 'd7', 'e7', 'f7', 'g6', 'h5', 'i4', 'k3', 'l2'] },
    { from: 'b7', direction: 5, expected: ['c6', 'd5', 'e4', 'f3', 'g1'] },
    { from: 'b7', direction: 6, expected: ['b6', 'b5', 'b4', 'b3', 'b2', 'b1'] },
    { from: 'b7', direction: 7, expected: ['a5'] },
    { from: 'b7', direction: 8, expected: ['a6'] },
    { from: 'b7', direction: 9, expected: [] },
    { from: 'b7', direction: 10, expected: [] },
    { from: 'b7', direction: 11, expected: [] },

    // { from: 'c8', direction: 0, expected: [] },
    // { from: 'c8', direction: 1, expected: [] },
    // { from: 'c8', direction: 2, expected: [] },
    // { from: 'c8', direction: 3, expected: [] },
    // { from: 'c8', direction: 4, expected: [] },
    // { from: 'c8', direction: 5, expected: [] },
    // { from: 'c8', direction: 6, expected: [] },
    // { from: 'c8', direction: 7, expected: [] },
    // { from: 'c8', direction: 8, expected: [] },
    // { from: 'c8', direction: 9, expected: [] },
    // { from: 'c8', direction: 10, expected: [] },
    // { from: 'c8', direction: 11, expected: [] },

    // { from: 'd9', direction: 0, expected: [] },
    // { from: 'd9', direction: 1, expected: [] },
    // { from: 'd9', direction: 2, expected: [] },
    // { from: 'd9', direction: 3, expected: [] },
    // { from: 'd9', direction: 4, expected: [] },
    // { from: 'd9', direction: 5, expected: [] },
    // { from: 'd9', direction: 6, expected: [] },
    // { from: 'd9', direction: 7, expected: [] },
    // { from: 'd9', direction: 8, expected: [] },
    // { from: 'd9', direction: 9, expected: [] },
    // { from: 'd9', direction: 10, expected: [] },
    // { from: 'd9', direction: 11, expected: [] },

    // { from: 'e10', direction: 0, expected: [] },
    // { from: 'e10', direction: 1, expected: [] },
    // { from: 'e10', direction: 2, expected: [] },
    // { from: 'e10', direction: 3, expected: [] },
    // { from: 'e10', direction: 4, expected: [] },
    // { from: 'e10', direction: 5, expected: [] },
    // { from: 'e10', direction: 6, expected: [] },
    // { from: 'e10', direction: 7, expected: [] },
    // { from: 'e10', direction: 8, expected: [] },
    // { from: 'e10', direction: 9, expected: [] },
    // { from: 'e10', direction: 10, expected: [] },
    // { from: 'e10', direction: 11, expected: [] },

    // { from: 'f11', direction: 0, expected: [] },
    // { from: 'f11', direction: 1, expected: [] },
    // { from: 'f11', direction: 2, expected: [] },
    // { from: 'f11', direction: 3, expected: [] },
    // { from: 'f11', direction: 4, expected: [] },
    // { from: 'f11', direction: 5, expected: [] },
    // { from: 'f11', direction: 6, expected: [] },
    // { from: 'f11', direction: 7, expected: [] },
    // { from: 'f11', direction: 8, expected: [] },
    // { from: 'f11', direction: 9, expected: [] },
    // { from: 'f11', direction: 10, expected: [] },
    // { from: 'f11', direction: 11, expected: [] },

    // { from: 'g10', direction: 0, expected: [] },
    // { from: 'g10', direction: 1, expected: [] },
    // { from: 'g10', direction: 2, expected: [] },
    // { from: 'g10', direction: 3, expected: [] },
    // { from: 'g10', direction: 4, expected: [] },
    // { from: 'g10', direction: 5, expected: [] },
    // { from: 'g10', direction: 6, expected: [] },
    // { from: 'g10', direction: 7, expected: [] },
    // { from: 'g10', direction: 8, expected: [] },
    // { from: 'g10', direction: 9, expected: [] },
    // { from: 'g10', direction: 10, expected: [] },
    // { from: 'g10', direction: 11, expected: [] },

    // { from: 'h9', direction: 0, expected: [] },
    // { from: 'h9', direction: 1, expected: [] },
    // { from: 'h9', direction: 2, expected: [] },
    // { from: 'h9', direction: 3, expected: [] },
    // { from: 'h9', direction: 4, expected: [] },
    // { from: 'h9', direction: 5, expected: [] },
    // { from: 'h9', direction: 6, expected: [] },
    // { from: 'h9', direction: 7, expected: [] },
    // { from: 'h9', direction: 8, expected: [] },
    // { from: 'h9', direction: 9, expected: [] },
    // { from: 'h9', direction: 10, expected: [] },
    // { from: 'h9', direction: 11, expected: [] },

    // { from: 'i8', direction: 0, expected: [] },
    // { from: 'i8', direction: 1, expected: [] },
    // { from: 'i8', direction: 2, expected: [] },
    // { from: 'i8', direction: 3, expected: [] },
    // { from: 'i8', direction: 4, expected: [] },
    // { from: 'i8', direction: 5, expected: [] },
    // { from: 'i8', direction: 6, expected: [] },
    // { from: 'i8', direction: 7, expected: [] },
    // { from: 'i8', direction: 8, expected: [] },
    // { from: 'i8', direction: 9, expected: [] },
    // { from: 'i8', direction: 10, expected: [] },
    // { from: 'i8', direction: 11, expected: [] },

    // { from: 'k7', direction: 0, expected: [] },
    // { from: 'k7', direction: 1, expected: [] },
    // { from: 'k7', direction: 2, expected: [] },
    // { from: 'k7', direction: 3, expected: [] },
    // { from: 'k7', direction: 4, expected: [] },
    // { from: 'k7', direction: 5, expected: [] },
    // { from: 'k7', direction: 6, expected: [] },
    // { from: 'k7', direction: 7, expected: [] },
    // { from: 'k7', direction: 8, expected: [] },
    // { from: 'k7', direction: 9, expected: [] },
    // { from: 'k7', direction: 10, expected: [] },
    // { from: 'k7', direction: 11, expected: [] },

    // { from: 'l6', direction: 0, expected: [] },
    // { from: 'l6', direction: 1, expected: [] },
    // { from: 'l6', direction: 2, expected: [] },
    // { from: 'l6', direction: 3, expected: [] },
    // { from: 'l6', direction: 4, expected: [] },
    // { from: 'l6', direction: 5, expected: [] },
    // { from: 'l6', direction: 6, expected: [] },
    // { from: 'l6', direction: 7, expected: [] },
    // { from: 'l6', direction: 8, expected: [] },
    // { from: 'l6', direction: 9, expected: [] },
    // { from: 'l6', direction: 10, expected: [] },
    // { from: 'l6', direction: 11, expected: [] },

    // { from: 'k1', direction: 0, expected: [] },
    // { from: 'k1', direction: 1, expected: [] },
    // { from: 'k1', direction: 2, expected: [] },
    // { from: 'k1', direction: 3, expected: [] },
    // { from: 'k1', direction: 4, expected: [] },
    // { from: 'k1', direction: 5, expected: [] },
    // { from: 'k1', direction: 6, expected: [] },
    // { from: 'k1', direction: 7, expected: [] },
    // { from: 'k1', direction: 8, expected: [] },
    // { from: 'k1', direction: 9, expected: [] },
    // { from: 'k1', direction: 10, expected: [] },
    // { from: 'k1', direction: 11, expected: [] },

    // { from: 'i1', direction: 0, expected: [] },
    // { from: 'i1', direction: 1, expected: [] },
    // { from: 'i1', direction: 2, expected: [] },
    // { from: 'i1', direction: 3, expected: [] },
    // { from: 'i1', direction: 4, expected: [] },
    // { from: 'i1', direction: 5, expected: [] },
    // { from: 'i1', direction: 6, expected: [] },
    // { from: 'i1', direction: 7, expected: [] },
    // { from: 'i1', direction: 8, expected: [] },
    // { from: 'i1', direction: 9, expected: [] },
    // { from: 'i1', direction: 10, expected: [] },
    // { from: 'i1', direction: 11, expected: [] },

    // { from: 'h1', direction: 0, expected: [] },
    // { from: 'h1', direction: 1, expected: [] },
    // { from: 'h1', direction: 2, expected: [] },
    // { from: 'h1', direction: 3, expected: [] },
    // { from: 'h1', direction: 4, expected: [] },
    // { from: 'h1', direction: 5, expected: [] },
    // { from: 'h1', direction: 6, expected: [] },
    // { from: 'h1', direction: 7, expected: [] },
    // { from: 'h1', direction: 8, expected: [] },
    // { from: 'h1', direction: 9, expected: [] },
    // { from: 'h1', direction: 10, expected: [] },
    // { from: 'h1', direction: 11, expected: [] },

    // { from: 'g1', direction: 0, expected: [] },
    // { from: 'g1', direction: 1, expected: [] },
    // { from: 'g1', direction: 2, expected: [] },
    // { from: 'g1', direction: 3, expected: [] },
    // { from: 'g1', direction: 4, expected: [] },
    // { from: 'g1', direction: 5, expected: [] },
    // { from: 'g1', direction: 6, expected: [] },
    // { from: 'g1', direction: 7, expected: [] },
    // { from: 'g1', direction: 8, expected: [] },
    // { from: 'g1', direction: 9, expected: [] },
    // { from: 'g1', direction: 10, expected: [] },
    // { from: 'g1', direction: 11, expected: [] },

    // { from: 'f1', direction: 0, expected: [] },
    // { from: 'f1', direction: 1, expected: [] },
    // { from: 'f1', direction: 2, expected: [] },
    // { from: 'f1', direction: 3, expected: [] },
    // { from: 'f1', direction: 4, expected: [] },
    // { from: 'f1', direction: 5, expected: [] },
    // { from: 'f1', direction: 6, expected: [] },
    // { from: 'f1', direction: 7, expected: [] },
    // { from: 'f1', direction: 8, expected: [] },
    // { from: 'f1', direction: 9, expected: [] },
    // { from: 'f1', direction: 10, expected: [] },
    // { from: 'f1', direction: 11, expected: [] },

    // { from: 'e1', direction: 0, expected: [] },
    // { from: 'e1', direction: 1, expected: [] },
    // { from: 'e1', direction: 2, expected: [] },
    // { from: 'e1', direction: 3, expected: [] },
    // { from: 'e1', direction: 4, expected: [] },
    // { from: 'e1', direction: 5, expected: [] },
    // { from: 'e1', direction: 6, expected: [] },
    // { from: 'e1', direction: 7, expected: [] },
    // { from: 'e1', direction: 8, expected: [] },
    // { from: 'e1', direction: 9, expected: [] },
    // { from: 'e1', direction: 10, expected: [] },
    // { from: 'e1', direction: 11, expected: [] },

    // { from: 'd1', direction: 0, expected: [] },
    // { from: 'd1', direction: 1, expected: [] },
    // { from: 'd1', direction: 2, expected: [] },
    // { from: 'd1', direction: 3, expected: [] },
    // { from: 'd1', direction: 4, expected: [] },
    // { from: 'd1', direction: 5, expected: [] },
    // { from: 'd1', direction: 6, expected: [] },
    // { from: 'd1', direction: 7, expected: [] },
    // { from: 'd1', direction: 8, expected: [] },
    // { from: 'd1', direction: 9, expected: [] },
    // { from: 'd1', direction: 10, expected: [] },
    // { from: 'd1', direction: 11, expected: [] },

    // { from: 'c1', direction: 0, expected: [] },
    // { from: 'c1', direction: 1, expected: [] },
    // { from: 'c1', direction: 2, expected: [] },
    // { from: 'c1', direction: 3, expected: [] },
    // { from: 'c1', direction: 4, expected: [] },
    // { from: 'c1', direction: 5, expected: [] },
    // { from: 'c1', direction: 6, expected: [] },
    // { from: 'c1', direction: 7, expected: [] },
    // { from: 'c1', direction: 8, expected: [] },
    // { from: 'c1', direction: 9, expected: [] },
    // { from: 'c1', direction: 10, expected: [] },
    // { from: 'c1', direction: 11, expected: [] },

    // { from: 'b1', direction: 0, expected: [] },
    // { from: 'b1', direction: 1, expected: [] },
    // { from: 'b1', direction: 2, expected: [] },
    // { from: 'b1', direction: 3, expected: [] },
    // { from: 'b1', direction: 4, expected: [] },
    // { from: 'b1', direction: 5, expected: [] },
    // { from: 'b1', direction: 6, expected: [] },
    // { from: 'b1', direction: 7, expected: [] },
    // { from: 'b1', direction: 8, expected: [] },
    // { from: 'b1', direction: 9, expected: [] },
    // { from: 'b1', direction: 10, expected: [] },
    // { from: 'b1', direction: 11, expected: [] },
  ]
  
  tests.forEach(t => {
    test(`${t.from} : ${t.direction} = ${t.expected.join(' → ')}`, () => {
      expect(walk(t.from, t.direction), `Board path ${t.from}:${t.direction} failed`).toEqual(t.expected)
    })
  })
})