import type { Vec } from '@/types'

/**
 * Board coordinates with their corresponding FEN position.
 */
export const coordinate = {
  f11: 0,
  e10: 1,
  f10: 2,
  g10: 3,
  d9: 4,
  e9: 5,
  f9: 6,
  g9: 7,
  h9: 8,
  c8: 9,
  d8: 10,
  e8: 11,
  f8: 12,
  g8: 13,
  h8: 14,
  i8: 15,
  b7: 16,
  c7: 17,
  d7: 18,
  e7: 19,
  f7: 20,
  g7: 21,
  h7: 22,
  i7: 23,
  k7: 24,
  a6: 25,
  b6: 26,
  c6: 27,
  d6: 28,
  e6: 29,
  f6: 30,
  g6: 31,
  h6: 32,
  i6: 33,
  k6: 34,
  l6: 35,
  a5: 36,
  b5: 37,
  c5: 38,
  d5: 39,
  e5: 40,
  f5: 41,
  g5: 42,
  h5: 43,
  i5: 44,
  k5: 45,
  l5: 46,
  a4: 47,
  b4: 48,
  c4: 49,
  d4: 50,
  e4: 51,
  f4: 52,
  g4: 53,
  h4: 54,
  i4: 55,
  k4: 56,
  l4: 57,
  a3: 58,
  b3: 59,
  c3: 60,
  d3: 61,
  e3: 62,
  f3: 63,
  g3: 64,
  h3: 65,
  i3: 66,
  k3: 67,
  l3: 68,
  a2: 69,
  b2: 70,
  c2: 71,
  d2: 72,
  e2: 73,
  f2: 74,
  g2: 75,
  h2: 76,
  i2: 77,
  k2: 78,
  l2: 79,
  a1: 80,
  b1: 81,
  c1: 82,
  d1: 83,
  e1: 84,
  f1: 85,
  g1: 86,
  h1: 87,
  i1: 88,
  k1: 89,
  l1: 90,
} as const

/**
 * This array describes the relationship of positions relative to one another.
 * Think of these like the hands of a clock, with the selected position at the center.
 * The first sibling is at 12 o'clock, the second is at 1 o'clock, and so on.
 */
export const board: Vec<91, Vec<12, typeof coordinate[keyof typeof coordinate] | null>> = [
  // f11
  [
    null,
    null,
    null,
    null,
    coordinate.g10,
    coordinate.g9,
    coordinate.f10,
    coordinate.e9,
    coordinate.e10,
    null,
    null,
    null,
  ],

  // e10
  [
    null,
    null,
    coordinate.f11,
    coordinate.g10,
    coordinate.f10,
    coordinate.f9,
    coordinate.e9,
    coordinate.d8,
    coordinate.d9,
    null,
    null,
    null,
  ],

  // f10
  [
    coordinate.f11,
    null,
    coordinate.g10,
    coordinate.h9,
    coordinate.g9,
    coordinate.g8,
    coordinate.f9,
    coordinate.e8,
    coordinate.e9,
    coordinate.d9,
    coordinate.e10,
    null,
  ],

  // g10
  [
    null,
    null,
    null,
    null,
    coordinate.h9,
    coordinate.h8,
    coordinate.g9,
    coordinate.f9,
    coordinate.f10,
    coordinate.e10,
    coordinate.f11,
    null,
  ],

  // d9
  [
    null,
    null,
    coordinate.e10,
    coordinate.f10,
    coordinate.e9,
    coordinate.e8,
    coordinate.d8,
    coordinate.c7,
    coordinate.c8,
    null,
    null,
    null,
  ],

  // e9
  [
    coordinate.e10,
    coordinate.f11,
    coordinate.f10,
    coordinate.g9,
    coordinate.f9,
    coordinate.f8,
    coordinate.e8,
    coordinate.d7,
    coordinate.d8,
    coordinate.c8,
    coordinate.d9,
    null,
  ],

  // f9
  [
    coordinate.f10,
    coordinate.g10,
    coordinate.g9,
    coordinate.h8,
    coordinate.g8,
    coordinate.g7,
    coordinate.f8,
    coordinate.e7,
    coordinate.e8,
    coordinate.d8,
    coordinate.e9,
    coordinate.e10,
  ],

  // g9
  [
    coordinate.g10,
    null,
    coordinate.h9,
    coordinate.i8,
    coordinate.h8,
    coordinate.h7,
    coordinate.g8,
    coordinate.f8,
    coordinate.f9,
    coordinate.e9,
    coordinate.f10,
    coordinate.f11,
  ],

  // h9
  [
    null,
    null,
    null,
    null,
    coordinate.i8,
    coordinate.i7,
    coordinate.h8,
    coordinate.g8,
    coordinate.g9,
    coordinate.f10,
    coordinate.g10,
    null,
  ],

  // c8
  [
    null,
    null,
    coordinate.d9,
    coordinate.e9,
    coordinate.d8,
    coordinate.d7,
    coordinate.c7,
    coordinate.b6,
    coordinate.b7,
    null,
    null,
    null,
  ],

  // d8
  [
    coordinate.d9,
    coordinate.e10,
    coordinate.e9,
    coordinate.f9,
    coordinate.e8,
    coordinate.e7,
    coordinate.d7,
    coordinate.c6,
    coordinate.c7,
    coordinate.b7,
    coordinate.c8,
    null,
  ],

  // e8
  [
    coordinate.e9,
    coordinate.f10,
    coordinate.f9,
    coordinate.g8,
    coordinate.f8,
    coordinate.f7,
    coordinate.e7,
    coordinate.d6,
    coordinate.d7,
    coordinate.c7,
    coordinate.d8,
    coordinate.d9,
  ],

  // f8
  [
    coordinate.f9,
    coordinate.g9,
    coordinate.g8,
    coordinate.h7,
    coordinate.g7,
    coordinate.g6,
    coordinate.f7,
    coordinate.e6,
    coordinate.e7,
    coordinate.d7,
    coordinate.e8,
    coordinate.e9,
  ],

  // g8
  [
    coordinate.g9,
    coordinate.h9,
    coordinate.h8,
    coordinate.i7,
    coordinate.h7,
    coordinate.h6,
    coordinate.g7,
    coordinate.f7,
    coordinate.f8,
    coordinate.e8,
    coordinate.f9,
    coordinate.f10,
  ],

  // h8
  [
    coordinate.h9,
    null,
    coordinate.i8,
    coordinate.k7,
    coordinate.i7,
    coordinate.i6,
    coordinate.h7,
    coordinate.g7,
    coordinate.g8,
    coordinate.f9,
    coordinate.g9,
    coordinate.g10,
  ],

  // i8
  [
    null,
    null,
    null,
    null,
    coordinate.k7,
    coordinate.k6,
    coordinate.i7,
    coordinate.h7,
    coordinate.h8,
    coordinate.g9,
    coordinate.h9,
    null,
  ],

  // b7
  [
    null,
    null,
    coordinate.c8,
    coordinate.d8,
    coordinate.c7,
    coordinate.c6,
    coordinate.b6,
    coordinate.a5,
    coordinate.a6,
    null,
    null,
    null,
  ],

  // c7
  [
    coordinate.c8,
    coordinate.d9,
    coordinate.d8,
    coordinate.e8,
    coordinate.d7,
    coordinate.d6,
    coordinate.c6,
    coordinate.b5,
    coordinate.b6,
    coordinate.a6,
    coordinate.b7,
    null,
  ],

  // d7
  [
    coordinate.d8,
    coordinate.e9,
    coordinate.e8,
    coordinate.f8,
    coordinate.e7,
    coordinate.e6,
    coordinate.d6,
    coordinate.c5,
    coordinate.c6,
    coordinate.b6,
    coordinate.c7,
    coordinate.c8,
  ],

  // e7
  [
    coordinate.e8,
    coordinate.f9,
    coordinate.f8,
    coordinate.g7,
    coordinate.f7,
    coordinate.f6,
    coordinate.e6,
    coordinate.d5,
    coordinate.d6,
    coordinate.c6,
    coordinate.d7,
    coordinate.d8,
  ],

  // f7
  [
    coordinate.f8,
    coordinate.g8,
    coordinate.g7,
    coordinate.h6,
    coordinate.g6,
    coordinate.g5,
    coordinate.f6,
    coordinate.e5,
    coordinate.e6,
    coordinate.d6,
    coordinate.e7,
    coordinate.e8,
  ],

  // g7
  [
    coordinate.g8,
    coordinate.h8,
    coordinate.h7,
    coordinate.i6,
    coordinate.h6,
    coordinate.h5,
    coordinate.g6,
    coordinate.f6,
    coordinate.f7,
    coordinate.e7,
    coordinate.f8,
    coordinate.f9,
  ],

  // h7
  [
    coordinate.h8,
    coordinate.i8,
    coordinate.i7,
    coordinate.k6,
    coordinate.i6,
    coordinate.i5,
    coordinate.h6,
    coordinate.g6,
    coordinate.g7,
    coordinate.f8,
    coordinate.g8,
    coordinate.g9,
  ],

  // i7
  [
    coordinate.i8,
    null,
    coordinate.k7,
    coordinate.l6,
    coordinate.k6,
    coordinate.k5,
    coordinate.i6,
    coordinate.h6,
    coordinate.h7,
    coordinate.g8,
    coordinate.h8,
    coordinate.h9,
  ],

  // k7
  [
    null,
    null,
    null,
    null,
    coordinate.l6,
    coordinate.l5,
    coordinate.k6,
    coordinate.i6,
    coordinate.i7,
    coordinate.h8,
    coordinate.i8,
    null,
  ],

  // a6
  [
    null,
    null,
    coordinate.b7,
    coordinate.c7,
    coordinate.b6,
    coordinate.b5,
    coordinate.a5,
    null,
    null,
    null,
    null,
    null,
  ],

  // b6
  [
    coordinate.b7,
    coordinate.c8,
    coordinate.c7,
    coordinate.d7,
    coordinate.c6,
    coordinate.c5,
    coordinate.b5,
    coordinate.a4,
    coordinate.a5,
    null,
    coordinate.a6,
    null,
  ],

  // c6
  [
    coordinate.c7,
    coordinate.d8,
    coordinate.d7,
    coordinate.e7,
    coordinate.d6,
    coordinate.d5,
    coordinate.c5,
    coordinate.b4,
    coordinate.b5,
    coordinate.a5,
    coordinate.b6,
    coordinate.b7,
  ],

  // d6
  [
    coordinate.d7,
    coordinate.e8,
    coordinate.e7,
    coordinate.f7,
    coordinate.e6,
    coordinate.e5,
    coordinate.d5,
    coordinate.c4,
    coordinate.c5,
    coordinate.b5,
    coordinate.c6,
    coordinate.c7,
  ],

  // e6
  [
    coordinate.e7,
    coordinate.f8,
    coordinate.f7,
    coordinate.g6,
    coordinate.f6,
    coordinate.f5,
    coordinate.e5,
    coordinate.d4,
    coordinate.d5,
    coordinate.c5,
    coordinate.d6,
    coordinate.d7,
  ],

  // f6
  [
    coordinate.f7,
    coordinate.g7,
    coordinate.g6,
    coordinate.h5,
    coordinate.g5,
    coordinate.g4,
    coordinate.f5,
    coordinate.e4,
    coordinate.e5,
    coordinate.d5,
    coordinate.e6,
    coordinate.e7,
  ],

  // g6
  [
    coordinate.g7,
    coordinate.h7,
    coordinate.h6,
    coordinate.i5,
    coordinate.h5,
    coordinate.h4,
    coordinate.g5,
    coordinate.f5,
    coordinate.f6,
    coordinate.e6,
    coordinate.f7,
    coordinate.f8,
  ],

  // h6
  [
    coordinate.h7,
    coordinate.i7,
    coordinate.i6,
    coordinate.k5,
    coordinate.i5,
    coordinate.i4,
    coordinate.h5,
    coordinate.g5,
    coordinate.g6,
    coordinate.f7,
    coordinate.g7,
    coordinate.g8,
  ],

  // i6
  [
    coordinate.i7,
    coordinate.k7,
    coordinate.k6,
    coordinate.l5,
    coordinate.k5,
    coordinate.k4,
    coordinate.i5,
    coordinate.h5,
    coordinate.h6,
    coordinate.g7,
    coordinate.h7,
    coordinate.h8,
  ],

  // k6
  [
    coordinate.k7,
    null,
    coordinate.l6,
    null,
    coordinate.l5,
    coordinate.l4,
    coordinate.k5,
    coordinate.i5,
    coordinate.i6,
    coordinate.h7,
    coordinate.i7,
    coordinate.i8,
  ],

  // l6
  [
    null,
    null,
    null,
    null,
    null,
    null,
    coordinate.l5,
    coordinate.k5,
    coordinate.k6,
    coordinate.i7,
    coordinate.k7,
    null,
  ],

  // a5
  [
    coordinate.a6,
    coordinate.b7,
    coordinate.b6,
    coordinate.c6,
    coordinate.b5,
    coordinate.b4,
    coordinate.a4,
    null,
    null,
    null,
    null,
    null,
  ],

  // b5
  [
    coordinate.b6,
    coordinate.c7,
    coordinate.c6,
    coordinate.d6,
    coordinate.c5,
    coordinate.c4,
    coordinate.b4,
    coordinate.a3,
    coordinate.a4,
    null,
    coordinate.a5,
    coordinate.a6,
  ],

  // c5
  [
    coordinate.c6,
    coordinate.d7,
    coordinate.d6,
    coordinate.e6,
    coordinate.d5,
    coordinate.d4,
    coordinate.c4,
    coordinate.b3,
    coordinate.b4,
    coordinate.a4,
    coordinate.b5,
    coordinate.b6,
  ],

  // d5
  [
    coordinate.d6,
    coordinate.e7,
    coordinate.e6,
    coordinate.f6,
    coordinate.e5,
    coordinate.e4,
    coordinate.d4,
    coordinate.c3,
    coordinate.c4,
    coordinate.b4,
    coordinate.c5,
    coordinate.c6,
  ],

  // e5
  [
    coordinate.e6,
    coordinate.f7,
    coordinate.f6,
    coordinate.g5,
    coordinate.f5,
    coordinate.f4,
    coordinate.e4,
    coordinate.d3,
    coordinate.d4,
    coordinate.c4,
    coordinate.d5,
    coordinate.d6,
  ],

  // f5
  [
    coordinate.f6,
    coordinate.g6,
    coordinate.g5,
    coordinate.h4,
    coordinate.g4,
    coordinate.g3,
    coordinate.f4,
    coordinate.e3,
    coordinate.e4,
    coordinate.d4,
    coordinate.e5,
    coordinate.e6,
  ],

  // g5
  [
    coordinate.g6,
    coordinate.h6,
    coordinate.h5,
    coordinate.i4,
    coordinate.h4,
    coordinate.h3,
    coordinate.g4,
    coordinate.f4,
    coordinate.f5,
    coordinate.e5,
    coordinate.f6,
    coordinate.f7,
  ],

  // h5
  [
    coordinate.h6,
    coordinate.i6,
    coordinate.i5,
    coordinate.k4,
    coordinate.i4,
    coordinate.i3,
    coordinate.h4,
    coordinate.g4,
    coordinate.g5,
    coordinate.f6,
    coordinate.g6,
    coordinate.g7,
  ],

  // i5
  [
    coordinate.i6,
    coordinate.k6,
    coordinate.k5,
    coordinate.l4,
    coordinate.k4,
    coordinate.k3,
    coordinate.i4,
    coordinate.h4,
    coordinate.h5,
    coordinate.g6,
    coordinate.h6,
    coordinate.h7,
  ],

  // k5
  [
    coordinate.k6,
    coordinate.l6,
    coordinate.l5,
    null,
    coordinate.l4,
    coordinate.l3,
    coordinate.k4,
    coordinate.i4,
    coordinate.i5,
    coordinate.h6,
    coordinate.i6,
    coordinate.i7,
  ],

  // l5
  [
    coordinate.l6,
    null,
    null,
    null,
    null,
    null,
    coordinate.l4,
    coordinate.k4,
    coordinate.k5,
    coordinate.i6,
    coordinate.k6,
    coordinate.k7,
  ],

  // a4
  [
    coordinate.a5,
    coordinate.b6,
    coordinate.b5,
    coordinate.c5,
    coordinate.b4,
    coordinate.b3,
    coordinate.a3,
    null,
    null,
    null,
    null,
    null,
  ],

  // b4
  [
    coordinate.b5,
    coordinate.c6,
    coordinate.c5,
    coordinate.d5,
    coordinate.c4,
    coordinate.c3,
    coordinate.b3,
    coordinate.a2,
    coordinate.a3,
    null,
    coordinate.a4,
    coordinate.a5,
  ],

  // c4
  [
    coordinate.c5,
    coordinate.d6,
    coordinate.d5,
    coordinate.e5,
    coordinate.d4,
    coordinate.d3,
    coordinate.c3,
    coordinate.b2,
    coordinate.b3,
    coordinate.a3,
    coordinate.b4,
    coordinate.b5,
  ],

  // d4
  [
    coordinate.d5,
    coordinate.e6,
    coordinate.e5,
    coordinate.f5,
    coordinate.e4,
    coordinate.e3,
    coordinate.d3,
    coordinate.c2,
    coordinate.c3,
    coordinate.b3,
    coordinate.c4,
    coordinate.c5,
  ],

  // e4
  [
    coordinate.e5,
    coordinate.f6,
    coordinate.f5,
    coordinate.g4,
    coordinate.f4,
    coordinate.f3,
    coordinate.e3,
    coordinate.d2,
    coordinate.d3,
    coordinate.c3,
    coordinate.d4,
    coordinate.d5,
  ],

  // f4
  [
    coordinate.f5,
    coordinate.g5,
    coordinate.g4,
    coordinate.h3,
    coordinate.g3,
    coordinate.g2,
    coordinate.f3,
    coordinate.e2,
    coordinate.e3,
    coordinate.d3,
    coordinate.e4,
    coordinate.e5,
  ],

  // g4
  [
    coordinate.g5,
    coordinate.h5,
    coordinate.h4,
    coordinate.i3,
    coordinate.h3,
    coordinate.h2,
    coordinate.g3,
    coordinate.f3,
    coordinate.f4,
    coordinate.e4,
    coordinate.f5,
    coordinate.f6,
  ],

  // h4
  [
    coordinate.h5,
    coordinate.i5,
    coordinate.i4,
    coordinate.k3,
    coordinate.i3,
    coordinate.i2,
    coordinate.h3,
    coordinate.g3,
    coordinate.g4,
    coordinate.f5,
    coordinate.g5,
    coordinate.g6,
  ],

  // i4
  [
    coordinate.i5,
    coordinate.k5,
    coordinate.k4,
    coordinate.l3,
    coordinate.k3,
    coordinate.k2,
    coordinate.i3,
    coordinate.h3,
    coordinate.h4,
    coordinate.g5,
    coordinate.h5,
    coordinate.h6,
  ],

  // k4
  [
    coordinate.k5,
    coordinate.l5,
    coordinate.l4,
    null,
    coordinate.l3,
    coordinate.l2,
    coordinate.k3,
    coordinate.i3,
    coordinate.i4,
    coordinate.h5,
    coordinate.i5,
    coordinate.i6,
  ],

  // l4
  [
    coordinate.l5,
    null,
    null,
    null,
    null,
    null,
    coordinate.l3,
    coordinate.k3,
    coordinate.k4,
    coordinate.i5,
    coordinate.k5,
    coordinate.k6,
  ],

  // a3
  [
    coordinate.a4,
    coordinate.b5,
    coordinate.b4,
    coordinate.c4,
    coordinate.b3,
    coordinate.b2,
    coordinate.a2,
    null,
    null,
    null,
    null,
    null,
  ],

  // b3
  [
    coordinate.b4,
    coordinate.c5,
    coordinate.c4,
    coordinate.d4,
    coordinate.c3,
    coordinate.c2,
    coordinate.b2,
    coordinate.a1,
    coordinate.a2,
    null,
    coordinate.a3,
    coordinate.a4,
  ],

  // c3
  [
    coordinate.c4,
    coordinate.d5,
    coordinate.d4,
    coordinate.e4,
    coordinate.d3,
    coordinate.d2,
    coordinate.c2,
    coordinate.b1,
    coordinate.b2,
    coordinate.a2,
    coordinate.b3,
    coordinate.b4,
  ],

  // d3
  [
    coordinate.d4,
    coordinate.e5,
    coordinate.e4,
    coordinate.f4,
    coordinate.e3,
    coordinate.e2,
    coordinate.d2,
    coordinate.c1,
    coordinate.c2,
    coordinate.b2,
    coordinate.c3,
    coordinate.c4,
  ],

  // e3
  [
    coordinate.e4,
    coordinate.f5,
    coordinate.f4,
    coordinate.g3,
    coordinate.f3,
    coordinate.f2,
    coordinate.e2,
    coordinate.d1,
    coordinate.d2,
    coordinate.c2,
    coordinate.d3,
    coordinate.d4,
  ],

  // f3
  [
    coordinate.f4,
    coordinate.g4,
    coordinate.g3,
    coordinate.h2,
    coordinate.g2,
    coordinate.g1,
    coordinate.f2,
    coordinate.e1,
    coordinate.e2,
    coordinate.d2,
    coordinate.e3,
    coordinate.e4,
  ],

  // g3
  [
    coordinate.g4,
    coordinate.h4,
    coordinate.h3,
    coordinate.i2,
    coordinate.h2,
    coordinate.h1,
    coordinate.g2,
    coordinate.f2,
    coordinate.f3,
    coordinate.e3,
    coordinate.f4,
    coordinate.f5,
  ],

  // h3
  [
    coordinate.h4,
    coordinate.i4,
    coordinate.i3,
    coordinate.k2,
    coordinate.i2,
    coordinate.i1,
    coordinate.h2,
    coordinate.g2,
    coordinate.g3,
    coordinate.f4,
    coordinate.g4,
    coordinate.g5,
  ],

  // i3
  [
    coordinate.i4,
    coordinate.k4,
    coordinate.k3,
    coordinate.l2,
    coordinate.k2,
    coordinate.k1,
    coordinate.i2,
    coordinate.h2,
    coordinate.h3,
    coordinate.g4,
    coordinate.h4,
    coordinate.h5,
  ],

  // k3
  [
    coordinate.k4,
    coordinate.l4,
    coordinate.l3,
    null,
    coordinate.l2,
    coordinate.l1,
    coordinate.k2,
    coordinate.i2,
    coordinate.i3,
    coordinate.h4,
    coordinate.i4,
    coordinate.i5,
  ],

  // l3
  [
    coordinate.l4,
    null,
    null,
    null,
    null,
    null,
    coordinate.l2,
    coordinate.k2,
    coordinate.k3,
    coordinate.i4,
    coordinate.k4,
    coordinate.k5,
  ],

  // a2
  [
    coordinate.a3,
    coordinate.b4,
    coordinate.b3,
    coordinate.c3,
    coordinate.b2,
    coordinate.b1,
    coordinate.a1,
    null,
    null,
    null,
    null,
    null,
  ],

  // b2
  [
    coordinate.b3,
    coordinate.c4,
    coordinate.c3,
    coordinate.d3,
    coordinate.c2,
    coordinate.c1,
    coordinate.b1,
    null,
    coordinate.a1,
    null,
    coordinate.a2,
    coordinate.a3,
  ],

  // c2
  [
    coordinate.c3,
    coordinate.d4,
    coordinate.d3,
    coordinate.e3,
    coordinate.d2,
    coordinate.d1,
    coordinate.c1,
    null,
    coordinate.b1,
    coordinate.a1,
    coordinate.b2,
    coordinate.b3,
  ],

  // d2
  [
    coordinate.d3,
    coordinate.e4,
    coordinate.e3,
    coordinate.f3,
    coordinate.e2,
    coordinate.e1,
    coordinate.d1,
    null,
    coordinate.c1,
    coordinate.b1,
    coordinate.c2,
    coordinate.c3,
  ],

  // e2
  [
    coordinate.e3,
    coordinate.f4,
    coordinate.f3,
    coordinate.g2,
    coordinate.f2,
    coordinate.f1,
    coordinate.e1,
    null,
    coordinate.d1,
    coordinate.c1,
    coordinate.d2,
    coordinate.d3,
  ],

  // f2
  [
    coordinate.f3,
    coordinate.g3,
    coordinate.g2,
    coordinate.h1,
    coordinate.g1,
    null,
    coordinate.f1,
    null,
    coordinate.e1,
    coordinate.d1,
    coordinate.e2,
    coordinate.e3,
  ],

  // g2
  [
    coordinate.g3,
    coordinate.h3,
    coordinate.h2,
    coordinate.i1,
    coordinate.h1,
    null,
    coordinate.g1,
    coordinate.f1,
    coordinate.f2,
    coordinate.e2,
    coordinate.f3,
    coordinate.f4,
  ],

  // h2
  [
    coordinate.h3,
    coordinate.i3,
    coordinate.i2,
    coordinate.k1,
    coordinate.i1,
    null,
    coordinate.h1,
    coordinate.g1,
    coordinate.g2,
    coordinate.f3,
    coordinate.g3,
    coordinate.g4,
  ],

  // i2
  [
    coordinate.i3,
    coordinate.k3,
    coordinate.k2,
    coordinate.l1,
    coordinate.k1,
    null,
    coordinate.i1,
    coordinate.h1,
    coordinate.h2,
    coordinate.g3,
    coordinate.h3,
    coordinate.h4,
  ],

  // k2
  [
    coordinate.k3,
    coordinate.l3,
    coordinate.l2,
    null,
    coordinate.l1,
    null,
    coordinate.k1,
    coordinate.i1,
    coordinate.i2,
    coordinate.h3,
    coordinate.i3,
    coordinate.i4,
  ],

  // l2
  [
    coordinate.l3,
    null,
    null,
    null,
    null,
    null,
    coordinate.l1,
    coordinate.k1,
    coordinate.k2,
    coordinate.i3,
    coordinate.k3,
    coordinate.k4,
  ],

  // a1
  [
    coordinate.a2,
    coordinate.b3,
    coordinate.b2,
    coordinate.c2,
    coordinate.b1,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],

  // b1
  [
    coordinate.b2,
    coordinate.c3,
    coordinate.c2,
    coordinate.d2,
    coordinate.c1,
    null,
    null,
    null,
    null,
    null,
    coordinate.a1,
    coordinate.a2,
  ],

  // c1
  [
    coordinate.c2,
    coordinate.d3,
    coordinate.d2,
    coordinate.e2,
    coordinate.d1,
    null,
    null,
    null,
    null,
    null,
    coordinate.b1,
    coordinate.b2,
  ],

  // d1
  [
    coordinate.d2,
    coordinate.e3,
    coordinate.e2,
    coordinate.f2,
    coordinate.e1,
    null,
    null,
    null,
    null,
    null,
    coordinate.c1,
    coordinate.c2,
  ],

  // e1
  [
    coordinate.e2,
    coordinate.f3,
    coordinate.f2,
    coordinate.g1,
    coordinate.f1,
    null,
    null,
    null,
    null,
    null,
    coordinate.d1,
    coordinate.d2,
  ],

  // f1
  [
    coordinate.f2,
    coordinate.g2,
    coordinate.g1,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    coordinate.e1,
    coordinate.e2,
  ],

  // g1
  [
    coordinate.g2,
    coordinate.h2,
    coordinate.h1,
    null,
    null,
    null,
    null,
    null,
    coordinate.f1,
    coordinate.e1,
    coordinate.f2,
    coordinate.f3,
  ],

  // h1
  [
    coordinate.h2,
    coordinate.i2,
    coordinate.i1,
    null,
    null,
    null,
    null,
    null,
    coordinate.g1,
    coordinate.f2,
    coordinate.g2,
    coordinate.g3,
  ],

  // i1
  [
    coordinate.i2,
    coordinate.k2,
    coordinate.k1,
    null,
    null,
    null,
    null,
    null,
    coordinate.h1,
    coordinate.g2,
    coordinate.h2,
    coordinate.h3,
  ],

  // k1
  [
    coordinate.k2,
    coordinate.l2,
    coordinate.l1,
    null,
    null,
    null,
    null,
    null,
    coordinate.i1,
    coordinate.h2,
    coordinate.i2,
    coordinate.i3,
  ],

  // l1
  [
    coordinate.l2,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    coordinate.k1,
    coordinate.i2,
    coordinate.k2,
    coordinate.k3,
  ],
] as const
